[config]
    url             = "http://localhost:9200"
    username        = ""
    password        = ""
    use-kibana      = false
    enabled-indices = ["rating", "transactions", "blocks", "validators", "miniblocks", "rounds", "accounts", "accountshistory", "receipts", "scresults", "accountsdct", "accountsdcthistory", "epochinfo", "scdeploys", "tokens", "tags", "logs", "delegators", "operations"]
